language: java

jdk:
  - oraclejdk8

before_install:
  - cp ./tools/ci/.travis.settings.xml $HOME/.m2/settings.xml
    && mvn -version

install:
  - mvn clean install -Pci-install -B -U -e
  - sh ./tools/check_format.sh

script:
  - travis_retry mvn clean package -Pci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
